services:

  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=admin123
      - MINIO_DOMAIN=minio
    networks:
      - dev-network 
    ports:
      - 9001:9001
      - 9000:9000
    command: ["server", "/data", "--console-address", ":9001"]
    restart: always

  mc:
    depends_on:
      - minio
    image: minio/mc
    container_name: mc
    networks:
      dev-network:
    environment:
      - AWS_ACCESS_KEY_ID=admin
      - AWS_SECRET_ACCESS_KEY=admin123
      - AWS_REGION=us-east-1
    entrypoint: |
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9000 admin admin123) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc rm -r --force minio/test;
      /usr/bin/mc mb minio/test;
      /usr/bin/mc policy set public minio/test;
      tail -f /dev/null
      "
    restart: always

networks:
  dev-network:
     external: true
